version: "3.7"
services:
  app:
    container_name: shopify
    build: ./challenge
    ports:
      - 5000:5000
    volumes:
      - ./challenge/app:/app
      - ./challenge/logs:/home/app/logs
      - ./challenge/supervisord.log:/home/app/supervisord.log
    entrypoint: supervisord -c /etc/supervisord.conf
