version: '3.7'

services:
  predict:
    container_name: predictor
    restart: unless-stopped
    build:
      context: ./challenge
      dockerfile: Dockerfile
    ports:
      - "6000:1337"
    privileged: true 