version: '3.7'

services:
  securesigning:
    container_name: securesigning
    restart: unless-stopped
    build:
      context: ./challenge
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    privileged: true 