version: '3.7'

services:
  revengesecuresigning:
    container_name: revengesecuresigning
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9500:9500"
    privileged: true 